[package]
name = "bmr-wireless-game-esp8266"
version = "0.1.0"
authors = ["Marko Viitanen <marko.viitanen@tuni.fi>"]
edition = "2018"

[dependencies]
#xtensa-lx-rt = "0.5.0"
#xtensa-lx = "0.3.0"
panic-halt = "0.2.0"
#esp8266-hal = "0.4.0"
